# Chapter 10: Matrix Multiplication

## 10.4 QR Factorization

Recall the Gram-Schmidt Algorithm from Chapter 5.4:
* If the collection of column vectors is linearly independent, the algorithm produces an orthonormal collection of vectors.
* Each column vector *ai* is a linear combination of the orthonormal vectors *q1 ... qi*
* Each othonormal vector *qi* is a linear combination of the original collection vectors *a1 ... ai*

The following is the algorithm derived from the Python Companion 5.4:

In [1]:
# Gram Schmidt Algorithm

import numpy as np
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
        #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependence
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
        #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q

In [3]:
A = np.array( [ [1, 0, 0,] , [2, 0, 3], [4, 5, 6] ] )
q = gram_schmidt(A)
print(q)

Vectors are linearly independent.
[array([1., 0., 0.]), array([0., 0., 1.]), array([0., 1., 0.])]


##### How are the Gram-Schmidt Algorithm and QR Factorization related?

We can define the QR factorization function using the Gram-Schmidt algorithm:

In [4]:
def QR_factorization(A): 
    Q = np.array(gram_schmidt(A)) 
    R = Q @ A
    return Q, R

The matrix Q is the same collection of orthonormal vectors the GS-Algorithm would find for a collection of linearly independent vectors. After all, these "collections" are merely matrices themselves: Vectors are matrices.

In [5]:
Q, R = QR_factorization(A)
print('Q')
print(Q)
print('R')
print(R)

print(Q@R)
print(A==Q@R)

Vectors are linearly independent.
Q
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
R
[[1. 0. 0.]
 [4. 5. 6.]
 [2. 0. 3.]]
[[1. 0. 0.]
 [2. 0. 3.]
 [4. 5. 6.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


The attributes of the matrices of Q and R come directly from the Gram-Schmidt Algorithm (VMLS p. 190). A is expressed as the product of a matrix Q of orthonormal columns and a matrix R, an upper triangular representation of A. 

##### How are the Gram Matrix and QR Factorization related?

QR Factorization is an application of Gram matrices whose columns are orthonormal. The Gram Matrix is defined as the inner product of a matrix with itself:
$G = A^{T}A$

In [6]:
print('Array A:')
print(A, '\n')
print('Array A.T:')
print(A.T, '\n')

G1 = A.T@A

print('Gram Matrix, G:')
print(G1)

Array A:
[[1 0 0]
 [2 0 3]
 [4 5 6]] 

Array A.T:
[[1 2 4]
 [0 0 5]
 [0 3 6]] 

Gram Matrix, G:
[[21 20 30]
 [20 25 30]
 [30 30 45]]


Inserting the QR factorization of A into the equation for the Gram Matrix, we have:

$G = (QR)^{T}QR$

Expanding on this equation further with properties of matrices, we can deduce a new identity:

$G = (R^{T})(Q^{T})QR = R^{T}(Q^{T}Q)R = R^{T}IR = R^{T}R$

This shows that the gram matrix of the original matrix A is equal to the gram matrix of its upper right triangular matrix R.

In [7]:
G2 = R.T@R
print(G2, '\n')

print(G1==G2)

[[21. 20. 30.]
 [20. 25. 30.]
 [30. 30. 45.]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Potential Discussion Questions

* The example worked out above is very clean in the sense that our orthogonal matrix Q essentially resembles unit vectors. However, this is generally a rarer case. It's not uncommon to have a matrix Q of decimal values that still consist of orthogonal values. Remembering the qualities that make orthogonal vectors, it can help to show yourself that Q consists of orthonormal columns. How does this influence the identity of R?

* The authors make mention that the GS-Algorithm designed in 5.4 finds the linear dependency of the *rows* while QR factorization seeks the linear dependency of the *columns*. So we insert the transpose into the QR Factorization to account for this instead. How does this influence the readability of our results? Are there any ways you could improve either algorithm to resolve this issue?



In [8]:
B = np.array( [ [2, 3] , [6, 8] ] )
print(B)
q = gram_schmidt(B)
print(q)

[[2 3]
 [6 8]]
Vectors are linearly independent.
[array([0.5547002 , 0.83205029]), array([ 0.83205029, -0.5547002 ])]


In [10]:
Q, R = QR_factorization(B)
print('Q')
print(Q)
print('R')
print(R)

Vectors are linearly independent.
Q
[[ 0.5547002   0.83205029]
 [ 0.83205029 -0.5547002 ]]
R
[[ 6.10170216  8.32050294]
 [-1.66410059 -1.94145069]]
