## Matrix-Vector/Matrix Multiplication (Ch6.4, Ch10)

When multiplying a Matrix and a Vector together, you should be thinking about this as simply Matrix-Matrix multiplication. After all, vectors and matrices are one in the same: you may have noticed by now that $n$-vectors are merely $n \times 1$ matrices! This should simplify much of how we think about resultant matrix outputs.

We've read that matrix multiplication *is not commutative*. This is because the dimensions of both matrices determine the dimensions of the output matrix. As you've read, to multiply two matrices together, the inner dimensions must match. In other words:

A matrix, $A$, with dimensions $m \times p$ can only be multiplied by another matrix, $B$, with dimensions $p \times n$. Again, in other words: *The first matrix must have the same number of columns as rows of the second matrix*.

Take the expression $y = Ax$.

* $A$ is an ($m \times n$) matrix.

* $x$ is an $n$-vector, or an $n \times 1$ matrix.

We can now see this as a legal operation: We are multiplying an $m \times n$ matrix with an $n \times 1$ matrix:

$m \times (n * n) \times 1$ --> inner dimensions are equal, and we will output a matrix with the outer dimensions.

The output, $y$, is an $m \times 1$ matrix, or an $m$-vector.

In [3]:
import numpy as np
A = np.array([[1,2],[3,4], [5, 6]])
x = np.array([2, 3])

print('Multiplying Ax:')
print('A =')
print(A)
print('x =')
print(x)
print('y = A @ x =', A@x)

## Causes a value error. We are attempting to multiply (n x 1) * (m x n). 
## The inner dimensions do not match. This operation is illegal!
# print(x @ A) 

Multiplying Ax:
A =
[[1 2]
 [3 4]
 [5 6]]
x =
[2 3]
y = A @ x = [ 8 18 28]


## Visualizing the Transpose

Transposing is an operation performed on matrices to invert its entries. Each entry $A_{ij}$ equals $A^{T}_{ji}$. 

In the grand scheme, rows become columns, columns become rows:
* First row becomes the first column in the transpose
* Second row becomes the second column in the transpose
* And so on...
Notice that **diagonal entries stay the same**.

In [12]:
T = np.array( [ [1, 10, 100],[2, 20, 200], [3, 30, 300] ] )
print('T =')
print(T, '\n')

T_t = T.T
print('T^T =')
print(T_transpose)

# Diagonal Entries are the same:
print('\nDiagonal Entries are the same:')
print('T[0][0] == T_t[0][0]')
print(T[0][0] == T_t[0][0])
print('T[1][1] == T_t[1][1]')
print(T[1][1] == T_t[1][1])

T =
[[  1  10 100]
 [  2  20 200]
 [  3  30 300]] 

T^T =
[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]

Diagonal Entries are the same:
T[0][0] == T_t[0][0]
True
T[1][1] == T_t[1][1]
True


Several operations work as a result of transposition because the dimensions of a matrix are reversed: an $m \times n$ matrix transposed becomes an $n \times m$ matrix.

If $A$ is an $m \times n$ matrix, its transpose, $A^{T}$ is an $n \times m$ matrix. Finding the inner product of the matrix $A$ is then as simple as multiplying its transpose with itself: $A^{T}A$

Before this, you've been transposing vectors without much thought as to what the $^{T}$ signified. Perhaps now the transpose of vectors makes even clearer sense. All you do when you transpose an $n$-vector is transform this column vector, which we know is an $n \times 1$ vector, into a $1 \times n$ row vector!

As a note, keep in mind that Python outputs row and column vectors the same way. Visually, they appear to represent the same thing, but the syntax and context is important to keep in mind.

In [16]:
n = np.array([1, 3])
n_t = n.T

print('n =')
print(n)
print('n_t =')
print(n_t, '\n')

print('Inner Product = n^t*n =')
print(np.inner(n, n_t))

n =
[1 3]
n_t =
[1 3] 

Inner Product = n^t*n =
10
